### ISSUE TITLE
bam mode not working

### ISSUE THREAD

**Issue by RJBeng** [katholt/sonneityping#4]
Hello, 

I am running into issues when using the --bam mode. This is my command:

`python sonnei_genotype.py --mode bam --bam *.bam --ref ref.fa --ref_id  HE616528 --allele_table alleles.txt --samtools_location ~/SOFTWARE/samtools-1.2/ --bcftools_location ~/SOFTWARE/bcftools-1.2/ --output genotypes.txt`

I get the following errors

```Traceback (most recent call last):
  File "sonnei_genotype.py", line 658, in <module>
    main()
  File "sonnei_genotype.py", line 501, in main
    ordered_loci = list(loci + qrdr_loci)
TypeError: can only concatenate list (not "dict") to list
```

The code is working for --vcf mode.

Many thanks
Rebecca

**Comment by jhawkey** [comment]
Hi Rebecca,

I suspect both of these issues are due to me playing around with the development branch working on future updates. The code in the dev branch currently isn’t stable.

However all the issues you raised before, as well as updating the code to find all mutations in the known gyrA and parC codons, have now been fixed in the master branch.

Could you please try your commands on the master branch instead?

Thanks!

Jane

**Comment by RJBeng** [comment]
Hi Jane, 

I just cloned the repository from the Github page and ran the code on my data. I am still getting the same errors for the bam and parsnp mode, the vcf mode is working though. 

Best 
Rebecca
